language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    # for building GHC
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - autoconf
    - automake
    - g++
    - gcc
    - git
    - libgmp-dev
    # - libllvm5.0
    - libnuma-dev
    - libtinfo-dev
    - libtool
    # - llvm-5.0
    # - llvm-5.0-dev
    - make
    - ncurses-dev
    - python3
    - realpath
    - xz-utils
    - zlib1g-dev

# TODO: also run checkbashisms.pl (currently two instances of non-compliance)
script:
 - ./.travis.sh

matrix:
  fast_finish: true
